# Generated by Django 4.0.4 on 2023-05-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persmenu',
            options={'ordering': ['pk'], 'verbose_name': 'Меню кабинета', 'verbose_name_plural': 'Меню кабинета'},
        ),
    ]
