# Generated by Django 4.0.4 on 2023-05-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rearward', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faks',
            options={'verbose_name': 'Аптечка', 'verbose_name_plural': 'Аптечки'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='medicines',
            options={'verbose_name': 'Средство', 'verbose_name_plural': 'Средства'},
        ),
        migrations.AddField(
            model_name='medicines',
            name='faks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='app_rearward.faks', verbose_name='Средства'),
            preserve_default=False,
        ),
    ]
