# Generated by Django 4.0.4 on 2023-05-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rearward', '0002_alter_faks_options_alter_locations_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='befo',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Годен до'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='faks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='app_rearward.faks', verbose_name='Средства'),
        ),
    ]
