# Generated by Django 4.0.4 on 2023-05-21 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_rearward', '0003_alter_medicines_befo_alter_medicines_faks'),
    ]

    operations = [
        migrations.AddField(
            model_name='faks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Средства'),
            preserve_default=False,
        ),
    ]
